// Code generated by "enumer -type=Field -output=aws/field/field_gen.go -linecomment ./aws/field"; DO NOT EDIT.

package field

import (
	"fmt"
	"strings"
)

const _FieldName = "SKUCapacityStatusGroupGroup DescriptionInstance TypeLocationOperating SystemoperationPre Installed S/WProduct FamilyserviceCodeTenancyusageTypeDescriptionCache Memory Size (GB)Volume API NameVolume TypeStorage ClassAccess TypeThroughput ClassCache EngineDatabase EngineDatabase EditionDeployment OptionLicense ModelFile system typeStorage typeThroughput capacityDeployment optionAlarm TypeCurrencyPricePerUnitStartingRangeTermTypeUnit"

var _FieldIndex = [...]uint16{0, 3, 17, 22, 39, 52, 60, 76, 85, 102, 116, 127, 134, 143, 154, 176, 191, 202, 215, 226, 242, 254, 269, 285, 302, 315, 331, 343, 362, 379, 389, 397, 409, 422, 430, 434}

const _FieldLowerName = "skucapacitystatusgroupgroup descriptioninstance typelocationoperating systemoperationpre installed s/wproduct familyservicecodetenancyusagetypedescriptioncache memory size (gb)volume api namevolume typestorage classaccess typethroughput classcache enginedatabase enginedatabase editiondeployment optionlicense modelfile system typestorage typethroughput capacitydeployment optionalarm typecurrencypriceperunitstartingrangetermtypeunit"

func (i Field) String() string {
	if i >= Field(len(_FieldIndex)-1) {
		return fmt.Sprintf("Field(%d)", i)
	}
	return _FieldName[_FieldIndex[i]:_FieldIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FieldNoOp() {
	var x [1]struct{}
	_ = x[SKU-(0)]
	_ = x[CapacityStatus-(1)]
	_ = x[Group-(2)]
	_ = x[GroupDescription-(3)]
	_ = x[InstanceType-(4)]
	_ = x[Location-(5)]
	_ = x[OperatingSystem-(6)]
	_ = x[Operation-(7)]
	_ = x[PreInstalledSW-(8)]
	_ = x[ProductFamily-(9)]
	_ = x[ServiceCode-(10)]
	_ = x[Tenancy-(11)]
	_ = x[UsageType-(12)]
	_ = x[Description-(13)]
	_ = x[CacheMemorySizeGB-(14)]
	_ = x[VolumeAPIName-(15)]
	_ = x[VolumeType-(16)]
	_ = x[StorageClass-(17)]
	_ = x[AccessType-(18)]
	_ = x[ThroughputClass-(19)]
	_ = x[CacheEngine-(20)]
	_ = x[DatabaseEngine-(21)]
	_ = x[DatabaseEdition-(22)]
	_ = x[DatabaseDeploymentOption-(23)]
	_ = x[LicenseModel-(24)]
	_ = x[FileSystemType-(25)]
	_ = x[StorageType-(26)]
	_ = x[ThroughputCapacity-(27)]
	_ = x[FileSystemDeploymentOption-(28)]
	_ = x[AlarmType-(29)]
	_ = x[Currency-(30)]
	_ = x[PricePerUnit-(31)]
	_ = x[StartingRange-(32)]
	_ = x[TermType-(33)]
	_ = x[Unit-(34)]
}

var _FieldValues = []Field{SKU, CapacityStatus, Group, GroupDescription, InstanceType, Location, OperatingSystem, Operation, PreInstalledSW, ProductFamily, ServiceCode, Tenancy, UsageType, Description, CacheMemorySizeGB, VolumeAPIName, VolumeType, StorageClass, AccessType, ThroughputClass, CacheEngine, DatabaseEngine, DatabaseEdition, DatabaseDeploymentOption, LicenseModel, FileSystemType, StorageType, ThroughputCapacity, FileSystemDeploymentOption, AlarmType, Currency, PricePerUnit, StartingRange, TermType, Unit}

var _FieldNameToValueMap = map[string]Field{
	_FieldName[0:3]:          SKU,
	_FieldLowerName[0:3]:     SKU,
	_FieldName[3:17]:         CapacityStatus,
	_FieldLowerName[3:17]:    CapacityStatus,
	_FieldName[17:22]:        Group,
	_FieldLowerName[17:22]:   Group,
	_FieldName[22:39]:        GroupDescription,
	_FieldLowerName[22:39]:   GroupDescription,
	_FieldName[39:52]:        InstanceType,
	_FieldLowerName[39:52]:   InstanceType,
	_FieldName[52:60]:        Location,
	_FieldLowerName[52:60]:   Location,
	_FieldName[60:76]:        OperatingSystem,
	_FieldLowerName[60:76]:   OperatingSystem,
	_FieldName[76:85]:        Operation,
	_FieldLowerName[76:85]:   Operation,
	_FieldName[85:102]:       PreInstalledSW,
	_FieldLowerName[85:102]:  PreInstalledSW,
	_FieldName[102:116]:      ProductFamily,
	_FieldLowerName[102:116]: ProductFamily,
	_FieldName[116:127]:      ServiceCode,
	_FieldLowerName[116:127]: ServiceCode,
	_FieldName[127:134]:      Tenancy,
	_FieldLowerName[127:134]: Tenancy,
	_FieldName[134:143]:      UsageType,
	_FieldLowerName[134:143]: UsageType,
	_FieldName[143:154]:      Description,
	_FieldLowerName[143:154]: Description,
	_FieldName[154:176]:      CacheMemorySizeGB,
	_FieldLowerName[154:176]: CacheMemorySizeGB,
	_FieldName[176:191]:      VolumeAPIName,
	_FieldLowerName[176:191]: VolumeAPIName,
	_FieldName[191:202]:      VolumeType,
	_FieldLowerName[191:202]: VolumeType,
	_FieldName[202:215]:      StorageClass,
	_FieldLowerName[202:215]: StorageClass,
	_FieldName[215:226]:      AccessType,
	_FieldLowerName[215:226]: AccessType,
	_FieldName[226:242]:      ThroughputClass,
	_FieldLowerName[226:242]: ThroughputClass,
	_FieldName[242:254]:      CacheEngine,
	_FieldLowerName[242:254]: CacheEngine,
	_FieldName[254:269]:      DatabaseEngine,
	_FieldLowerName[254:269]: DatabaseEngine,
	_FieldName[269:285]:      DatabaseEdition,
	_FieldLowerName[269:285]: DatabaseEdition,
	_FieldName[285:302]:      DatabaseDeploymentOption,
	_FieldLowerName[285:302]: DatabaseDeploymentOption,
	_FieldName[302:315]:      LicenseModel,
	_FieldLowerName[302:315]: LicenseModel,
	_FieldName[315:331]:      FileSystemType,
	_FieldLowerName[315:331]: FileSystemType,
	_FieldName[331:343]:      StorageType,
	_FieldLowerName[331:343]: StorageType,
	_FieldName[343:362]:      ThroughputCapacity,
	_FieldLowerName[343:362]: ThroughputCapacity,
	_FieldName[362:379]:      FileSystemDeploymentOption,
	_FieldLowerName[362:379]: FileSystemDeploymentOption,
	_FieldName[379:389]:      AlarmType,
	_FieldLowerName[379:389]: AlarmType,
	_FieldName[389:397]:      Currency,
	_FieldLowerName[389:397]: Currency,
	_FieldName[397:409]:      PricePerUnit,
	_FieldLowerName[397:409]: PricePerUnit,
	_FieldName[409:422]:      StartingRange,
	_FieldLowerName[409:422]: StartingRange,
	_FieldName[422:430]:      TermType,
	_FieldLowerName[422:430]: TermType,
	_FieldName[430:434]:      Unit,
	_FieldLowerName[430:434]: Unit,
}

var _FieldNames = []string{
	_FieldName[0:3],
	_FieldName[3:17],
	_FieldName[17:22],
	_FieldName[22:39],
	_FieldName[39:52],
	_FieldName[52:60],
	_FieldName[60:76],
	_FieldName[76:85],
	_FieldName[85:102],
	_FieldName[102:116],
	_FieldName[116:127],
	_FieldName[127:134],
	_FieldName[134:143],
	_FieldName[143:154],
	_FieldName[154:176],
	_FieldName[176:191],
	_FieldName[191:202],
	_FieldName[202:215],
	_FieldName[215:226],
	_FieldName[226:242],
	_FieldName[242:254],
	_FieldName[254:269],
	_FieldName[269:285],
	_FieldName[285:302],
	_FieldName[302:315],
	_FieldName[315:331],
	_FieldName[331:343],
	_FieldName[343:362],
	_FieldName[362:379],
	_FieldName[379:389],
	_FieldName[389:397],
	_FieldName[397:409],
	_FieldName[409:422],
	_FieldName[422:430],
	_FieldName[430:434],
}

// FieldString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FieldString(s string) (Field, error) {
	if val, ok := _FieldNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FieldNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Field values", s)
}

// FieldValues returns all values of the enum
func FieldValues() []Field {
	return _FieldValues
}

// FieldStrings returns a slice of all String values of the enum
func FieldStrings() []string {
	strs := make([]string, len(_FieldNames))
	copy(strs, _FieldNames)
	return strs
}

// IsAField returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Field) IsAField() bool {
	for _, v := range _FieldValues {
		if i == v {
			return true
		}
	}
	return false
}
